//
//  CategoriesPresenter.swift
//  leboncoin
//
//  Created by Lassad Tiss on 16/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoriesPresentationLogic
{
  func presentSomething(response: Categories.Something.Response)
}

class CategoriesPresenter: CategoriesPresentationLogic
{
  weak var viewController: CategoriesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Categories.Something.Response)
  {
    let viewModel = Categories.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
